const API_BASE_URL= "https://api.openweathermap.org/data/2.5/forecast/daily"
const API_KEY="145c88693b59f60ceb8f9f1aefb9e926"
const DEFAULT_TABLE_ELEMENTS_PER_PAGE = 5
const USE_PAGINATION_ON_TABLE = true

export {API_BASE_URL, API_KEY, DEFAULT_TABLE_ELEMENTS_PER_PAGE, USE_PAGINATION_ON_TABLE }